### PR TITLE
Bug fix 24 12 05

### PR DESCRIPTION
**Pull request by yyngfive**

### CODE REVIEW

**Comment by ssuleman1992** [comment]
How to download scifig extension, please guide

**Comment by yyngfive** [comment]
> How to download scifig extension, please guide

If you are an Edge user, just download it from the microsoft addon store. if you are using Chrome, download the zip file from the release page, unzip it. Then open your Chrome extension manager page `chrome://extensions/`, enable the developer mode and load the unpacked extension folder. 
And I will upload this extension to Chrome web store after some time.

**Comment by yyngfive** [comment]
now, you can download this extension from chrome web store

**Comment by ssuleman1992** [comment]
> now, you can download this extension from chrome web store

I am still unable to download, please give me the download link

**Comment by yyngfive** [comment]
Just search the name on the chrome web store website. https://chromewebstore.google.com/detail/sci-fig-downloader/dooahdhpalnmkjkmdnhchoihgfmhfjkj

**Comment by yyngfive** [comment]
And new questions should be posted on the issues page

**Pull request merged**
